---
- name: Ensure all groups are created
  ansible.builtin.group:
    name: "{{ item }}"
  loop:
    - docker
    - samba
    - "{{ username }}"

- name: Create non-root user
  ansible.builtin.user:
    name: "{{ username }}"
    password: "{{password | password_hash('sha512')}}"
    groups:
      - sudo
      - docker
      - users
    append: true
    shell: "{{ shell }}"
    update_password: on_create

- name: Enable passwordless sudo for "{{ username }}"
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "usr/sbin/visudo -cf %s"

- name: Hushlogin
  file:
    path: "/home/{{ username }}./hushlogin"
    mode: 0644
    owner: "{{ username }}"
    group: "{{ username }}"
    modification_time: preserve
    access_time: preserve
    state: touch
